### ISSUE TITLE
Incorrect display in dark mode

### ISSUE THREAD

**Issue by LF-XiaofeiShao** [batikansosun/NetGuard#1]
My App only supports dark mode, in dark mode, I can't distinguish between text and background.

<img src="https://user-images.githubusercontent.com/105257642/204722280-0fe02465-8d76-4f70-af56-e254fc2dae99.PNG" width=300>

<img src="https://user-images.githubusercontent.com/105257642/204723294-d58a524b-8b7d-4e9c-808a-0c86e15ee076.jpg" width=300>

**Comment by batikansosun** [comment]
Fixed.  v2.3




![Simulator Screen Shot - iPhone 14 Pro - 2023-01-03 at 21 06 25](https://user-images.githubusercontent.com/10993355/210416012-a6671fbf-fd03-40e2-95b1-052288223bd0.png)
![Simulator Screen Shot - iPhone 14 Pro - 2023-01-03 at 21 06 34](https://user-images.githubusercontent.com/10993355/210416022-45ef58db-3b20-43e7-b2d8-1f664e8276bd.png)

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-03 at 21 06 17](https://user-images.githubusercontent.com/10993355/210416005-26098bc2-cf2e-424b-ab1c-798ee9a1fe71.png)

**Comment by LF-XiaofeiShao** [comment]
Looks great, thanks!
